const CATEGORIES = [
  "Accommodations",
  "Adventure",
  "Art and architecture",
  "Backpacking",
  "Beaches",
  "Camping",
  "City Exploration",
  "Cultural",
  "Family-Friendly",
  "Festival and Events",
  "Food and Drink",
  "Hidden Gems",
  "Hiking and Trekking",
  "History",
  "Money",
  "Mountains",
  "Nature",
  "Nightlife",
  "Outdoor activities",
  "Photography",
  "Road Trip",
  "Safety",
  "Save Money",
  "Scam",
  "Scenic Views",
  "Secret Spots",
  "Shopping",
  "Tips",
  "Transportation",
  "Volunteer and Community Work",
  "Wellness and Relaxation",
  "Wildlife",
];

export const CATEGORIES_OPTIONS = CATEGORIES.map((category) => {
  return {
    label: category,
    value: category,
  };
});
